### ISSUE TITLE
Filter by createdDateTime doesn't seem to work

### ISSUE THREAD

**Issue by StephenFerrero** [microsoftgraph/security-api-solutions#23]
### Problem
In the security-api-solutions repo query examples, there is a query example that doesn't seem to work properly.

security-api-solutions/Queries/README.md
https://github.com/microsoftgraph/security-api-solutions/tree/master/Queries/README.md

> Alerts created in a certain time interval | /security/alerts?$filter=createdDateTime gt 2019-04-01T00:00:00.000Z and createdDateTime lt 2019-05-05T00:00:00.000Z | Change date time (e.g. 2019-04-01T00:00:00.000Z) accordingly and/or use just eq, gt and lt
> -- | -- | --

### Expected results
I expected to only receive alerts which have a createdDateTime value falling between the two date provided in the filter.

### Repro
Following this example with this sample query:
`https://graph.microsoft.com/v1.0/security/alerts?$filter=createdDateTime gt 2019-09-10T00:00:00.000Z and createdDateTime lt 2019-10-01T00:00:00.000Z`

The results seem unfiltered, I am receiving results with a createdDateTime outside the specific filter range.

#### Sample results

See the createdDateTime value below:

`{
            "id": "REDACTED",
            "azureTenantId": "REDACTED",
            "azureSubscriptionId": null,
            "riskScore": null,
            "tags": [],
            "activityGroupName": null,
            "assignedTo": null,
            "category": "ThreatManagement",
            "closedDateTime": null,
            "comments": [
                "New alert"
            ],
            "confidence": null,
            "createdDateTime": "2019-08-15T10:49:07.817Z",
            "description": "Emails with phish URLs that were delivered and later removed -V1.0.0.3",
            "detectionIds": [],
            "eventDateTime": "2019-08-15T10:30:20Z",
            "feedback": null,
            "lastModifiedDateTime": "2019-08-15T10:50:47.383Z",
            "recommendedActions": [],
            "severity": "informational",
            "sourceMaterials": [],
            "status": "newAlert",
            "title": "Email messages containing phish URLs removed after delivery",
            "vendorInformation": {
                "provider": "Office 365 Security and Compliance",
                "providerVersion": null,
                "subProvider": null,
                "vendor": "Microsoft"
            },`

**Comment by preetikr** [comment]
There's a bug with Office365 provider for this issue - We are working with the Office provider to fix this. Are you able to see alerts from other providers with the createdDateTime $filter?

**Comment by benattimi** [comment]
Good morning.
I'm facing the same result with Audit Logs (_https://graph.microsoft.com/v1.0/auditLogs/signIns_). Frankly it seems to be a whole GRAPH API problem. I hope it will be solved soon, I'm waiting.

**Comment by pkhabazi** [comment]
I'm facing the same issue on v1.0 and beta version of the Security API, @preetikr is there any update regarding this issue?

**Comment by chinguyen1** [comment]
@pkhabazi Can you please let us know with what providers you have issue seeing the alerts using createdDateTime $filter? If it's Office 365, we are still working with the Office team to help land this.

**Comment by benattimi** [comment]
Good morning.
I had faced that problem working with Microsoft Graph “against” AAD but I solved it using the format yyyy-mm-ddThh:mm:ss followed by a “Z” .
Next week I’m starting to work with Graph and Office365, I hope to be able to manage the date filters in the same way.

Regards,
Michele


Michele Benatti
System Engineer

michele.benatti@sedoc.it<mailto:michele.benatti@sedoc.it>
+39 338-9428030

 [cid:logo_sedoc_311595f3-0b84-47b5-a8b6-a1edff76d442.png]

Sedoc Digital Group S.r.l. Via Brigata Reggio, 37 - 42124, Reggio Emilia
P: +39 0522 385011 | W: www.sedocdigitalgroup.it<http://www.sedocdigitalgroup.it/>  | M: info@sedocdigitalgroup.it<http://info@sedocdigitalgroup.it/>

[cid:linea_e3522618-3155-4723-b78c-9d0c681b5e09.png]


Le informazioni contenute in questa comunicazione e relativi allegati possono essere riservate e sono, comunque, destinate esclusivamente ai destinatari sopraindicati. La diffusione, distribuzione e/o copiatura del documento trasmesso da parte di qualsiasi soggetto diverso dal destinatario è vietata ai sensi del Regolamento UE 2016/679 (GDPR). Se avete ricevuto questo messaggio per errore, vi preghiamo di distruggerlo informandoci immediatamente scrivendoci una mail all'indirizzo info@sedocdigitalgroup.it. Per visualizzare l'informativa sul trattamento dei dati personali effettuato da Sedoc Digital Group S.r.l. consultare la nostra Privacy Policy<https://urlsand.esvalabs.com/?u=http%3A%2F%2Fwww.sedocdigitalgroup.it%2Fprivacy&e=daab5244&h=d3ae4337&f=n&p=y>.


[cid:loghi_multiazienda_19f866bb-bff0-4f07-9f4a-f4ff00c950db.png]

Da: chinguyen1 <notifications@github.com>
Inviato: giovedì 21 novembre 2019 19:26
A: microsoftgraph/security-api-solutions <security-api-solutions@noreply.github.com>
Cc: Michele Benatti <michele.benatti@sedoc.it>; Comment <comment@noreply.github.com>
Oggetto: Re: [microsoftgraph/security-api-solutions] Filter by createdDateTime doesn't seem to work (#23)


@pkhabazi<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fpkhabazi&e=6127e441&h=d6026fdb&f=n&p=y> Can you please let us know with what providers you have issue seeing the alerts using createdDateTime $filter? If it's Office 365, we are still working with the Office team to help land this.

**Comment by preetikr** [comment]
@pkhabazi @benattimi @StephenFerrero - Office team is working on fixing the support for createdDateTime for Microsoft Graph Security API alerts (Office365 ATP provider). This issue should be resolved by summer of this year. Thanks, for reporting this issue.

**Comment by pkhabazi** [comment]
@preetikr thanks for the update 👍

**Comment by jgularte** [comment]
I am still receiving pretty unusual responses from the O365 provider when using the filter on createdDateTime. When querying for the last day of alerts **_/alerts?$filter=createdDateTime gt 2020-06-25T14:40:29Z_** I expect to see two alerts that I manually triggered. Instead I receive alerts from 0365 with createdDateTimes from May (along with those two expected alerts). Any update would be much appreciated @preetikr

**Comment by jasonmcheong** [comment]
I am experiencing filtering issues as well when using the audit logs endpoint **/v1.0/auditLogs/signIns?$filter=createdDateTime gt 2020-11-04T12:00:00Z**. The audit logs returned exceed 500,000 records no matter the filter which is simply not manageable for our use case. @preetikr any idea when we can expect a fix?

**Comment by jeanchavez** [comment]
Hi @StephenFerrero 

The auditLogs/signIns Graph API only supports the operators eq, le, ge for the attribute createdDateTime, and your are using gt and lt that are not supported. check the MS documentation for more details

https://docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-1.0&tabs=http

**Comment by Manvityagi** [comment]
@jeanchavez The Microsoft documentation you attached does not mention anywhere that auditLogs/signIns Graph API only supports the operators eq, le, ge for the attribute createdDateTime.

**Comment by wfairc** [comment]
> Hi @StephenFerrero
> 
> The auditLogs/signIns Graph API only supports the operators eq, le, ge for the attribute createdDateTime, and your are using gt and lt that are not supported. check the MS documentation for more details
> 
> https://docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-1.0&tabs=http

I hope this is not true...  how is one to trust an API that doesn't support a full set of operators?
